name: Commit-crtiq
description: AI code reviewer using Metas Llama v2.
inputs:
  PR_AUTHOR_GITHUB_ID: 
    description: Your github ID
    required: true
runs: 
  using: "python"
  main: "src/commenter.py"
branding:
  icon: 'check'
  color: 'white'
  
