name: 'PR Reviewer'
description: 'Review pull requests and add comments'

inputs:
  pr-author-github-id:
    description: 'GitHub ID of the pull request author'
    required: true
    default: ${{ github.actor }}

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Find GitHub ID of PR author
      run: echo "PR author: ${{ inputs.pr-author-github-id }}"

    - name: Checkout pull request HEAD
      id: checkout_pr_head
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Print diff
      shell: bash
      run: |
        git fetch origin main
        git diff origin/main..HEAD > difference_hunk.txt
        find . -type f -name difference_hunk.txt
        pwd
        echo "difference hunk = "
        cat difference_hunk.txt

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.HOME }}/.cache/pip
        key: ${{ runner.os }}-dependencies-${{ hashFiles('requirements.txt') }}-{{ fileset.modifiedTime('requirements.txt') }}

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python src/commenter.py

    - name: Read PR comment from file
      run: cat src/files/output.txt > pr_comment.txt

    - name: Add PR comment
      uses: mshick/add-pr-comment@v2
      with:
        message-path: pr_comment.txt
        repo-directory: './'
        requirements-path: 'requirements.txt'
